#!/bin/bash

remote=$(jq -c '.remoteGitDependencies | to_entries | .[]' package.json)

for row in $remote; do
  repo=$(echo "${row}" | jq -r '.key | split("#") | .[0]')
  subDir=$(echo "${row}" | jq -r '.key | split("#") | .[1]')
  sha=$(echo "${row}" | jq -r .value)

  mkdir -p "remote/$repo"
  cd "remote/$repo"
  git init --quiet
  git remote add origin "https://github.com/$repo"
  git fetch --depth 1 origin $sha
  git config core.sparseCheckout true
  echo $subDir >> .git/info/sparse-checkout
  git pull origin $sha
  cd -
done

